file_format: "1"
id: corax
name: Corax
type: shield
url: https://github.com/dnlbauer/corax-keyboard
requires: [pro_micro]
features:
  - keys
  - encoder
siblings:
  - corax_left
  - corax_right
  - corax_dongle
